spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST:localhost}:${TEST_DB_PORT:5433}/${TEST_DB_NAME}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASS}
  jpa:
    show-sql: true

logging:
  level:
   com.wildtrack: DEBUG
