spring:
  application:
    name: wildtrack
  datasource:
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  threads:
    virtual:
      enabled: true

movebank:
  username: ${MOVEBANK_USERNAME}
  password: ${MOVEBANK_PASSWORD}

server:
  port: 8080
  servlet:
    context-path: /

scheduler:
  cronTime: "0 30 23 * * ?"
  enabled: true

app:
  wildtrack-api:
    base-url: https://api.wildtrack.com

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}.%M -- %msg%n"